trigger:
  - main
  - staging
  - dev
pr:
  - main
  - staging
  - dev

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - template: ./build-job-template.yml
        parameters:
          jobName: 'Build'
          nodeVersion: '14.x'
  - stage: Analyze
    jobs:
      - template: ./code-coverage-analysis-template.yml
        parameters:
          serviceConnection: 'Forge-SonarCloud'
          organization: '1058-sophia-gavrila-forge'
          projectKey: '1058-Sophia-Gavrila-Forge_Portfolio-Frontend'
          projectName: 'Portfolio-Frontend'
  - stage: Dockerize
    jobs:
      - template: ./dockerize-template.yml
        parameters:
          jobName: 'Dockerize'
          containerRegistry: 'acr-team2'
          repository: 'forge-frontend'
          dockerPath: '**/Dockerfile'
  - stage: Deploy
    jobs:
      - template: ./kubernetes-template.yml
        parameters:
          jobName: 'Deploy'
          branchMain: 'refs/heads/main'
          serviceConnectionMain: 'may24-devops-team2-main-cluster'
          serviceConnectionDev: 'may24-devops-team2-dev-cluster'
          manifestPath: '**/frontend_manifest.yml'
      - template: ./discord-job-template.yml
        parameters:
          dependOn: Deploy
          name: 'Team2-P3-Frontend'
          title: 'Forge Portfolio Management System DevOps'
          discordVarGroup: Discord-Webhook-Info
    
        