trigger:
  - main
  - staging
  - dev
pr:
  - main
  - staging
  - dev

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build_and_Test
    jobs:
      - template: ./build-job-template.yml
        parameters:
          jobName: 'Build'
          nodeVersion: '14.x'
  - stage: Dockerize
    jobs:
      - template: ./dockerize-template.yml
        parameters:
          jobName: 'Dockerize'
          containerRegistry: 'project-3-docker-hub'
          repository: 'dajpearl/forge-frontend'
          dockerPath: '**/Dockerfile'
  - stage: Deploy
    jobs:
      - template: ./kubernetes-template.yml
        parameters:
          jobName: Deploy
          serviceConnection: 'Alex-Dev-Cluster'
          manifestPath: '**/frontend_manifest.yml'
      - template: ./discord-job-template.yml
        parameters:
          dependOn: Deploy
          name: 'Team2-P3-Frontend'
          title: 'Forge Portfolio Management System DevOps'
          discordVarGroup: Discord-Webhook-Info
