trigger:
  - main
  - dev

pr:
  - main
  - dev

pool:
  vmImage: ubuntu-latest

parameters:
  - name: 'branchMain'
    type: string
    default: 'refs/heads/main'
  - name: 'branchDev'
    type: string
    default: 'refs/heads/dev'
- name: 'mainCluster' 
    type: string
    default: 'may24-devops-team2-main-cluster'
  - name: 'devCluster' 
    type: string
    default: 'may24-devops-team2-dev-cluster'
  - name: 'containerRegistry'
    type: string
    default: 'acr-team2'
  - name: 'repository'
    type: string
    default: 'forge-frontend'

stages:
  - stage: Build
    jobs:
      - template: ./build-job-template.yml
        parameters:
          jobName: 'Build'
          nodeVersion: '14.x'
  
  - stage: Analyze
    jobs:
      - template: ./code-coverage-analysis-template.yml
        parameters:
          serviceConnection: 'Forge-SonarCloud'
          organization: '1058-sophia-gavrila-forge'
          projectKey: '1058-Sophia-Gavrila-Forge_Portfolio-Frontend'
          projectName: 'Portfolio-Frontend'
  
  - stage: Dockerize
    jobs:
      - template: ./dockerize-template.yml
        parameters:
          jobName: 'Dockerize'
          containerRegistry: ${{parameters.containerRegistry}}
          repository: $${{parameters.repository}}
          imageTag: 'latest'
          dockerPath: '**/Dockerfile'
          dockerContext: ${{ variables.Build.Repository.LocalPath }}
  
  - stage: Deploy
    condition: > 
      and( succeeded(), 
      ne(variables['Build.Reason'], 'PullRequest'), 
      in( variables['Build.SourceBranch'], '${{parameters.branchMain}}', '${{parameters.branchDev}}' ) )
    jobs:
      - template: ./kubernetes-template.yml
        parameters:
          jobName: 'Deploy'
          ${{ if eq(variables['Build.SourceBranch'], parameters.branchMain) }}:
            clusterServiceConnection: 'may24-devops-team2-main-cluster'
          ${{ if ne(variables['Build.SourceBranch'], parameters.branchMain) }}:
            clusterServiceConnection: 'may24-devops-team2-dev-cluster'
          manifestPath: '**/frontend_manifest.yaml'
          containerRegistry: '${{ parameters.containerRegistry }}'
          namespace: 'team2'
          secretName: 'p3-team2-acr'


  - stage: Notify
    condition: always()
    jobs:
      - template: ./discord-job-template.yml
        parameters:
          name: 'Team2-P3-Frontend'
          title: 'Forge Portfolio Management System DevOps'
          discordVarGroup: Discord-Webhook-Info
            # parameters.discordVarGroup contains the name of a variable group set in Azure Pipelines > Library
            # the variable group contains two variables: discordid and discordkey
            # currently, the discordVarGroup is named Discord-Webhook-Info, 
            # but can be swapped out if you want to notify to multiple Discord webhooks.
