trigger:
  - main
  - staging
  - dev
pr:
  - main
  - staging
  - dev

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - template: ./build-job-template.yml
        parameters:
          jobName: 'Build'
          nodeVersion: '14.x'
  

