parameters:
  - name: 'jobName'
    type: string
  - name: 'nodeVersion'
    type: string
jobs:
  - job: ${{ parameters.jobName }}
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '${{ parameters.nodeVersion }}'
        displayName: 'Install Node.js'

      - script: |
          npm ci
          npm run build
          npm test -- --watchAll=false
        displayName: 'npm install build test'
