<<<<<<< HEAD
parameters:
  - name: 'jobName'
    type: string
  - name: 'nodeVersion'
    type: string
jobs:
  - job: ${{ parameters.jobName }}
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '${{ parameters.nodeVersion }}'
        displayName: 'Install Node.js'
      - script: npm ci
        displayName: 'npm install'
      - script: npm run build
        displayName: 'npm build'
=======
parameters:
  - name: 'jobName'
    type: string
  - name: 'nodeVersion'
    type: string
jobs:
  - job: ${{ parameters.jobName }}
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '${{ parameters.nodeVersion }}'
        displayName: 'Install Node.js'

      - script: npm ci
        displayName: npm ci
      
      - script: npm run build
        displayName: npm build
      
      - script: npm test -- --watchAll=false
        displayName: 'npm test'
>>>>>>> 633a6104d67d1c9fa9658ee45c7fcad228310ddf
