jobs:
  - job: DiscordMessage
    dependsOn: ${{ parameters.dependOn }}
    variables: 
    - group: Discord-Webhook-Info
    steps: 
    - task: ado-discord-webhook@1
      inputs:
        channelId: $env:discord_id
        webhookKey: $env:discord_key
        name: 'Team2-P3'
        messageType: 'content'
        content: |
          **Team 2 Project 3 Frontend**: $(Build.SourceVersionMessage)
          ```
          Build Number: $(Build.BuildNumber)
          Build Branch: $(Build.SourceBranch)
          Build Reason: $(Build.Reason)
          Build Image: frontend-$(Build.SourceVersion)
          ```
          **Result**: $(Agent.JobStatus)
      env:
        discord_id: $(discordid)
        discord_key: $(discordkey)
