parameters:
  - name: 'dependOn'
    type: string
  - name: 'name'
    type: string
  - name: 'title'
    type: string
  - name: 'discordVarGroup'
    type: string
jobs:
  - job: DiscordMessage
    variables: 
      - group: ${{parameters.discordVarGroup}}
    dependsOn: ${{ parameters.dependOn }}
    steps:  
      - task: ado-discord-webhook@1
        inputs:
          channelId: '$(discordid)'
          webhookKey: '$(discordkey)'
          name: ${{ parameters.name }}
          messageType: 'content'
          content: |
            **${{ parameters.title }}**: $(Build.SourceVersionMessage)
            ```
            Build Number: $(Build.BuildNumber)
            Build Branch: $(Build.SourceBranch)
            Build Reason: $(Build.Reason)
            Commit Id: $(Build.SourceVersion)
            ```
            **Result**: $(Agent.JobStatus)
