apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-frontend
spec:
  selector:
    matchLabels:
      app: portfolio-frontend
  template:
    metadata:
      labels:
        app: portfolio-frontend
    spec:
      containers:
      - name: portfolio-frontend
        image: #placeholder/image:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        # env:
        # envFrom:
        # - configmapRef:
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: portfolio-frontend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP