parameters:
  - name: 'jobName'
    type: string
  - name: 'nodeVersion'
    type: string
jobs:
  - job: ${{ parameters.jobName }}
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '${{ parameters.nodeVersion }}'
        displayName: 'Install Node.js'

      - script: npm ci
        displayName: npm ci
      
      - script: npm run-script build
        displayName: npm build
      
